INSERT INTO `webservice`.`positions` (`ID`, `NAME`) VALUES
(-1, 'WSTRZYMANE'),
(1, 'FREZERNIA'),
(2, 'CZYSZCZENIE'),
(3, 'PODKLADOWANIE'),
(4, 'SZLIFOWANIE'),
(5, 'LAKIEROWANIE'),
(6, 'POLEROWANIE'),
(7, 'PAKOWANIE');

