CREATE TABLE `workers` (
 `ID` int(10) NOT NULL,
 `NAME` varchar(255) NOT NULL,
 `SURNAME` varchar(255) NOT NULL,
 `POSITION` int(10) NOT NULL,
 `CODE` smallint(6) NOT NULL AUTO_INCREMENT,
 `active` smallint(1) NOT NULL DEFAULT '1',
 PRIMARY KEY (`CODE`),
 UNIQUE KEY `Identyfikator` (`ID`)
) 


CREATE TABLE `orders` (
 `ID` bigint(11) NOT NULL AUTO_INCREMENT,
 `ORDER_ID` varchar(255) NOT NULL,
 `CUSTOMER` varchar(255) NOT NULL,
 `AMOUNT` int(10) unsigned NOT NULL,
 `COLOR` varchar(255) NOT NULL,
 `STAGE` int(10) NOT NULL DEFAULT '1',
 `MISSING` smallint(2) NOT NULL DEFAULT '0',
 `EXPRESS` smallint(2) NOT NULL DEFAULT '0',
 `DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `LAST_UPDATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (`ID`)
) 

CREATE TABLE `events` (
 `ORDER_ID` bigint(20) NOT NULL,
 `STAGE` int(11) NOT NULL,
 `WORKER` smallint(6) NOT NULL,
 `DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `MISSING` int(10) unsigned NOT NULL DEFAULT '0',
 PRIMARY KEY (`ORDER_ID`,`STAGE`),
 KEY `WORKER` (`WORKER`),
 CONSTRAINT `events_ibfk_1` FOREIGN KEY (`ORDER_ID`) REFERENCES `orders` (`ID`),
 CONSTRAINT `workers` FOREIGN KEY (`WORKER`) REFERENCES `workers` (`CODE`)
) 